import { ScaledSheet } from "react-native-size-matters";
export const Styles = ScaledSheet.create({
  Container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#000000",
  },
  Text72: {
    fontSize: "72@ms",
    color: "white",
    fontFamily: "SGTMid",
    textAlign: "center",
  },
  Text64: {
    fontSize: "64@ms",
    color: "white",
    fontFamily: "SGTMid",
    textAlign: "center",
  },
  Text48: {
    fontSize: "48@ms",
    color: "white",
    fontFamily: "SGTMid",
    textAlign: "center",
  },
  Text40: {
    fontSize: "40@ms",
    color: "white",
    fontFamily: "SGTMid",
    textAlign: "center",
  },
  Text32: {
    fontSize: "32@ms",
    color: "white",
    fontFamily: "SGTMid",
    textAlign: "center",
  },
  Text24: {
    color: "white",
    fontSize: "24@ms",
    fontFamily: "SGTMid",
    textAlign: "center",
  },
  Pad20: {
    paddingVertical: "20@ms",
  },
  Mg20: {
    marginVertical: "20@ms",
    textAlign: "center",
  },
  Mg40: {
    marginVertical: "40@ms",
  },
  MgT16: {
    marginTop: "16@ms",
    textAlign: "center",
  },
  MgT64: {
    marginTop: "48@ms",
  },
  Reg: {
    fontFamily: "SGTReg",
  },
  TextInput: {
    fontSize: "32@ms",
    fontFamily: "SGTMid",
    color: "#FFFFFF",
    textAlign: "center",
    borderRadius: "16@ms",
    width: "260@ms",
    height: "84@ms",
  },
  Submit: {
    justifyContent: "center",
    alignItems: "center",
    width: "260@ms",
    height: "108@ms",
    backgroundColor: "#555555",
    marginTop: "36@ms",
    borderRadius: "16@ms",
  },
  Choose: {
    alignItems: "center",
    justifyContent: "center",
    width: "260@ms",
    height: "240@ms",
    borderRadius: "24@ms",
    marginVertical: "28@ms",
  },
  GlobalBackButton: {
    borderRadius: "8@ms",
    position: "absolute",
    width: "48@ms",
    height: "44@ms",
    top: "8@ms",
    left: "12@ms",
    zIndex: 20,
  },
  GlobalSeatPos: {
    borderRadius: "8@ms",
    position: "absolute",
    width: "64@ms",
    height: "48@ms",
    top: "20@ms",
    right: "24@ms",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#444444",
    zIndex: 20,
  },
  //

  NumPad: {
    width: "80@ms",
    height: "80@ms",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#666666",
    borderRadius: "20@ms",
    borderWidth: "4@ms",
    borderColor: "#DDDDDD",
    margin: "8@ms",
  },
  GoButton: {
    width: "260@ms",
    height: "80@ms",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: "16@ms",
    borderRadius: "16@ms",
    borderWidth: "4@ms",
  },
  DelButton: {
    fontSize: "60@ms",
    fontFamily: "THSrBold",
    color: "white",
    marginTop: "-4@ms",
  },
  //
  X20Pixel: {
    width: "60@ms",
    height: "64@ms",
    border: 1,
    borderColor: "gray",
    borderWidth: "2@ms",
    borderRadius: "4@ms",
    margin: "4@ms",
    justifyContent: "center",
  },
  X1Pixel: {
    width: "280@ms",
    height: "280@ms",
    marginVertical: "12@ms",
    borderRadius: "16@ms",
  },
  //
  ImgX20: {
    width: "320@ms",
    height: "160@ms",
  },
  ImgX1: {
    width: "280@ms",
    height: "120@ms",
  },
  LoadingBox: {
    width: "280@ms",
    height: "280@ms",
    textAlign: "center",
  },
  //
  AlertBox: {
    width: "280@ms",
    height: "160@ms",
    backgroundColor: "#222222",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "16@ms",
  },
  AlertContainer: {
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    width: "100%",
    height: "100%",
  },
});
